# anzsic_sectors.py
# M&A Sector mapping for ANZSIC 2006 (Revision 2.0) codes
# Custom mapping designed for at-a-glance M&A deal reporting
# Maps Division (letter), Subdivision (2-digit), Group (3-digit)
# and Class (4-digit) codes to 25 distinct M&A sector labels
#
# Design principles:
#   - Mining sub-types (iron, gold, gravel) → single "Mining" label
#   - Financial services split into 7 sub-sectors including Superannuation
#   - Healthcare split into Hospitals / Medical / Dental / Aged Care / Pharmacy
#   - Technology separated from Telecommunications and from Media
#   - Automotive retail separated from general retail
#   - Fuel retail separated (Ampol-type deals)
#   - Oil & Gas and Coal separated from broader Mining
#   - Veterinary separated from Professional Services
#   - Gambling separated from broader Arts and Recreation
#
# Usage in scraper.py:
#   from anzsic_sectors import get_ma_sector
#   sector = get_ma_sector("6330")  → "Superannuation"
#   sector = get_ma_sector("6322")  → "General Insurance"
#   sector = get_ma_sector("K")     → "Financial and Insurance Services" (fallback)

ANZSIC_TO_MA_SECTOR = {
    "01": "Agriculture and Agribusiness",
    "011": "Agriculture and Agribusiness",
    "0111": "Agriculture and Agribusiness",
    "0112": "Agriculture and Agribusiness",
    "0113": "Agriculture and Agribusiness",
    "0114": "Agriculture and Agribusiness",
    "0115": "Agriculture and Agribusiness",
    "012": "Agriculture and Agribusiness",
    "0121": "Agriculture and Agribusiness",
    "0122": "Agriculture and Agribusiness",
    "0123": "Agriculture and Agribusiness",
    "013": "Agriculture and Agribusiness",
    "0131": "Agriculture and Agribusiness",
    "0132": "Agriculture and Agribusiness",
    "0133": "Agriculture and Agribusiness",
    "0134": "Agriculture and Agribusiness",
    "0135": "Agriculture and Agribusiness",
    "0136": "Agriculture and Agribusiness",
    "0137": "Agriculture and Agribusiness",
    "0139": "Agriculture and Agribusiness",
    "014": "Agriculture and Agribusiness",
    "0141": "Agriculture and Agribusiness",
    "0142": "Agriculture and Agribusiness",
    "0143": "Agriculture and Agribusiness",
    "0144": "Agriculture and Agribusiness",
    "0145": "Agriculture and Agribusiness",
    "0146": "Agriculture and Agribusiness",
    "0149": "Agriculture and Agribusiness",
    "015": "Agriculture and Agribusiness",
    "0151": "Agriculture and Agribusiness",
    "0152": "Agriculture and Agribusiness",
    "0159": "Agriculture and Agribusiness",
    "016": "Agriculture and Agribusiness",
    "0160": "Agriculture and Agribusiness",
    "017": "Agriculture and Agribusiness",
    "0171": "Agriculture and Agribusiness",
    "0172": "Agriculture and Agribusiness",
    "018": "Agriculture and Agribusiness",
    "0180": "Agriculture and Agribusiness",
    "019": "Agriculture and Agribusiness",
    "0191": "Agriculture and Agribusiness",
    "0192": "Agriculture and Agribusiness",
    "0193": "Agriculture and Agribusiness",
    "0199": "Agriculture and Agribusiness",
    "02": "Agriculture and Agribusiness",
    "020": "Agriculture and Agribusiness",
    "0201": "Agriculture and Agribusiness",
    "0202": "Agriculture and Agribusiness",
    "0203": "Agriculture and Agribusiness",
    "03": "Agriculture and Agribusiness",
    "030": "Agriculture and Agribusiness",
    "0301": "Agriculture and Agribusiness",
    "0302": "Agriculture and Agribusiness",
    "04": "Agriculture and Agribusiness",
    "041": "Agriculture and Agribusiness",
    "0411": "Agriculture and Agribusiness",
    "0412": "Agriculture and Agribusiness",
    "0413": "Agriculture and Agribusiness",
    "0414": "Agriculture and Agribusiness",
    "0419": "Agriculture and Agribusiness",
    "042": "Agriculture and Agribusiness",
    "0420": "Agriculture and Agribusiness",
    "05": "Agriculture and Agribusiness",
    "051": "Agriculture and Agribusiness",
    "0510": "Agriculture and Agribusiness",
    "052": "Agriculture and Agribusiness",
    "0521": "Agriculture and Agribusiness",
    "0522": "Agriculture and Agribusiness",
    "0529": "Agriculture and Agribusiness",
    "06": "Coal Mining",
    "060": "Coal Mining",
    "0600": "Coal Mining",
    "07": "Oil and Gas",
    "070": "Oil and Gas",
    "0700": "Oil and Gas",
    "08": "Mining",
    "080": "Mining",
    "0801": "Mining",
    "0802": "Mining",
    "0803": "Mining",
    "0804": "Mining",
    "0805": "Mining",
    "0806": "Mining",
    "0807": "Mining",
    "0809": "Mining",
    "09": "Mining",
    "091": "Mining",
    "0911": "Mining",
    "0919": "Mining",
    "099": "Mining",
    "0990": "Mining",
    "10": "Mining",
    "101": "Mining",
    "1011": "Mining",
    "1012": "Mining",
    "109": "Mining",
    "1090": "Mining",
    "11": "Food and Beverage Manufacturing",
    "111": "Food and Beverage Manufacturing",
    "1111": "Food and Beverage Manufacturing",
    "1112": "Food and Beverage Manufacturing",
    "1113": "Food and Beverage Manufacturing",
    "112": "Food and Beverage Manufacturing",
    "1120": "Food and Beverage Manufacturing",
    "113": "Food and Beverage Manufacturing",
    "1131": "Food and Beverage Manufacturing",
    "1132": "Food and Beverage Manufacturing",
    "1133": "Food and Beverage Manufacturing",
    "114": "Food and Beverage Manufacturing",
    "1140": "Food and Beverage Manufacturing",
    "115": "Food and Beverage Manufacturing",
    "1150": "Food and Beverage Manufacturing",
    "116": "Food and Beverage Manufacturing",
    "1161": "Food and Beverage Manufacturing",
    "1162": "Food and Beverage Manufacturing",
    "117": "Food and Beverage Manufacturing",
    "1171": "Food and Beverage Manufacturing",
    "1172": "Food and Beverage Manufacturing",
    "1173": "Food and Beverage Manufacturing",
    "1174": "Food and Beverage Manufacturing",
    "118": "Food and Beverage Manufacturing",
    "1181": "Food and Beverage Manufacturing",
    "1182": "Food and Beverage Manufacturing",
    "119": "Food and Beverage Manufacturing",
    "1191": "Food and Beverage Manufacturing",
    "1192": "Food and Beverage Manufacturing",
    "1199": "Food and Beverage Manufacturing",
    "12": "Food and Beverage Manufacturing",
    "121": "Food and Beverage Manufacturing",
    "1211": "Food and Beverage Manufacturing",
    "1212": "Food and Beverage Manufacturing",
    "1213": "Food and Beverage Manufacturing",
    "1214": "Food and Beverage Manufacturing",
    "122": "Food and Beverage Manufacturing",
    "1220": "Food and Beverage Manufacturing",
    "13": "Manufacturing",
    "131": "Manufacturing",
    "1311": "Manufacturing",
    "1312": "Manufacturing",
    "1313": "Manufacturing",
    "132": "Manufacturing",
    "1320": "Manufacturing",
    "133": "Manufacturing",
    "1331": "Manufacturing",
    "1332": "Manufacturing",
    "1333": "Manufacturing",
    "1334": "Manufacturing",
    "134": "Manufacturing",
    "1340": "Manufacturing",
    "135": "Manufacturing",
    "1351": "Manufacturing",
    "1352": "Manufacturing",
    "14": "Manufacturing",
    "141": "Manufacturing",
    "1411": "Manufacturing",
    "1412": "Manufacturing",
    "1413": "Manufacturing",
    "149": "Manufacturing",
    "1491": "Manufacturing",
    "1492": "Manufacturing",
    "1493": "Manufacturing",
    "1494": "Manufacturing",
    "1499": "Manufacturing",
    "15": "Manufacturing",
    "151": "Manufacturing",
    "1510": "Manufacturing",
    "152": "Manufacturing",
    "1521": "Manufacturing",
    "1522": "Manufacturing",
    "1523": "Manufacturing",
    "1524": "Manufacturing",
    "1529": "Manufacturing",
    "16": "Manufacturing",
    "161": "Manufacturing",
    "1611": "Manufacturing",
    "1612": "Manufacturing",
    "162": "Manufacturing",
    "1620": "Manufacturing",
    "17": "Manufacturing",
    "170": "Manufacturing",
    "1701": "Manufacturing",
    "1709": "Manufacturing",
    "18": "Manufacturing",
    "181": "Manufacturing",
    "1811": "Manufacturing",
    "1812": "Manufacturing",
    "1813": "Manufacturing",
    "182": "Manufacturing",
    "1821": "Manufacturing",
    "1829": "Manufacturing",
    "183": "Manufacturing",
    "1831": "Manufacturing",
    "1832": "Manufacturing",
    "184": "Pharmaceutical Manufacturing",
    "1841": "Pharmaceutical Manufacturing",
    "1842": "Pharmaceutical Manufacturing",
    "185": "Manufacturing",
    "1851": "Manufacturing",
    "1852": "Manufacturing",
    "189": "Manufacturing",
    "1891": "Manufacturing",
    "1892": "Manufacturing",
    "1899": "Manufacturing",
    "19": "Manufacturing",
    "191": "Manufacturing",
    "1911": "Manufacturing",
    "1912": "Manufacturing",
    "1913": "Manufacturing",
    "1914": "Manufacturing",
    "1915": "Manufacturing",
    "1916": "Manufacturing",
    "1919": "Manufacturing",
    "192": "Manufacturing",
    "1920": "Manufacturing",
    "20": "Manufacturing",
    "201": "Manufacturing",
    "2010": "Manufacturing",
    "202": "Manufacturing",
    "2021": "Manufacturing",
    "2029": "Manufacturing",
    "203": "Manufacturing",
    "2031": "Manufacturing",
    "2032": "Manufacturing",
    "2033": "Manufacturing",
    "2034": "Manufacturing",
    "209": "Manufacturing",
    "2090": "Manufacturing",
    "21": "Manufacturing",
    "211": "Manufacturing",
    "2110": "Manufacturing",
    "212": "Manufacturing",
    "2121": "Manufacturing",
    "2122": "Manufacturing",
    "213": "Manufacturing",
    "2131": "Manufacturing",
    "2132": "Manufacturing",
    "2133": "Manufacturing",
    "2139": "Manufacturing",
    "214": "Manufacturing",
    "2141": "Manufacturing",
    "2142": "Manufacturing",
    "2149": "Manufacturing",
    "22": "Manufacturing",
    "221": "Manufacturing",
    "2210": "Manufacturing",
    "222": "Manufacturing",
    "2221": "Manufacturing",
    "2222": "Manufacturing",
    "2223": "Manufacturing",
    "2224": "Manufacturing",
    "2229": "Manufacturing",
    "223": "Manufacturing",
    "2231": "Manufacturing",
    "2239": "Manufacturing",
    "224": "Manufacturing",
    "2240": "Manufacturing",
    "229": "Manufacturing",
    "2291": "Manufacturing",
    "2292": "Manufacturing",
    "2293": "Manufacturing",
    "2299": "Manufacturing",
    "23": "Automotive Manufacturing",
    "231": "Automotive Manufacturing",
    "2311": "Automotive Manufacturing",
    "2312": "Automotive Manufacturing",
    "2313": "Automotive Manufacturing",
    "2319": "Automotive Manufacturing",
    "239": "Automotive Manufacturing",
    "2391": "Automotive Manufacturing",
    "2392": "Automotive Manufacturing",
    "2393": "Automotive Manufacturing",
    "2394": "Automotive Manufacturing",
    "2399": "Automotive Manufacturing",
    "24": "Manufacturing",
    "241": "Manufacturing",
    "2411": "Manufacturing",
    "2412": "Manufacturing",
    "2419": "Manufacturing",
    "242": "Manufacturing",
    "2421": "Manufacturing",
    "2422": "Manufacturing",
    "2429": "Manufacturing",
    "243": "Manufacturing",
    "2431": "Manufacturing",
    "2432": "Manufacturing",
    "2439": "Manufacturing",
    "244": "Manufacturing",
    "2441": "Manufacturing",
    "2449": "Manufacturing",
    "245": "Manufacturing",
    "2451": "Manufacturing",
    "2452": "Manufacturing",
    "246": "Manufacturing",
    "2461": "Manufacturing",
    "2462": "Manufacturing",
    "2463": "Manufacturing",
    "2469": "Manufacturing",
    "249": "Manufacturing",
    "2491": "Manufacturing",
    "2499": "Manufacturing",
    "25": "Manufacturing",
    "251": "Manufacturing",
    "2511": "Manufacturing",
    "2512": "Manufacturing",
    "2513": "Manufacturing",
    "2519": "Manufacturing",
    "259": "Manufacturing",
    "2591": "Manufacturing",
    "2592": "Manufacturing",
    "2599": "Manufacturing",
    "26": "Energy and Utilities",
    "261": "Energy and Utilities",
    "2611": "Energy and Utilities",
    "2612": "Energy and Utilities",
    "2619": "Energy and Utilities",
    "262": "Energy and Utilities",
    "2620": "Energy and Utilities",
    "263": "Energy and Utilities",
    "2630": "Energy and Utilities",
    "264": "Energy and Utilities",
    "2640": "Energy and Utilities",
    "27": "Energy and Utilities",
    "270": "Energy and Utilities",
    "2700": "Energy and Utilities",
    "28": "Energy and Utilities",
    "281": "Energy and Utilities",
    "2811": "Energy and Utilities",
    "2812": "Energy and Utilities",
    "29": "Waste and Environmental Services",
    "291": "Waste and Environmental Services",
    "2911": "Waste and Environmental Services",
    "2919": "Waste and Environmental Services",
    "292": "Waste and Environmental Services",
    "2921": "Waste and Environmental Services",
    "2922": "Waste and Environmental Services",
    "30": "Construction and Engineering",
    "301": "Construction and Engineering",
    "3011": "Construction and Engineering",
    "3019": "Construction and Engineering",
    "302": "Construction and Engineering",
    "3020": "Construction and Engineering",
    "31": "Construction and Engineering",
    "310": "Construction and Engineering",
    "3101": "Construction and Engineering",
    "3109": "Construction and Engineering",
    "32": "Construction and Engineering",
    "321": "Construction and Engineering",
    "3211": "Construction and Engineering",
    "3212": "Construction and Engineering",
    "322": "Construction and Engineering",
    "3221": "Construction and Engineering",
    "3222": "Construction and Engineering",
    "3223": "Construction and Engineering",
    "3224": "Construction and Engineering",
    "323": "Construction and Engineering",
    "3231": "Construction and Engineering",
    "3232": "Construction and Engineering",
    "3233": "Construction and Engineering",
    "3234": "Construction and Engineering",
    "3239": "Construction and Engineering",
    "324": "Construction and Engineering",
    "3241": "Construction and Engineering",
    "3242": "Construction and Engineering",
    "3243": "Construction and Engineering",
    "3244": "Construction and Engineering",
    "3245": "Construction and Engineering",
    "329": "Construction and Engineering",
    "3291": "Construction and Engineering",
    "3292": "Construction and Engineering",
    "3299": "Construction and Engineering",
    "33": "Wholesale Trade",
    "331": "Wholesale Trade",
    "3311": "Wholesale Trade",
    "3312": "Wholesale Trade",
    "3319": "Wholesale Trade",
    "332": "Wholesale Trade",
    "3321": "Wholesale Trade",
    "3322": "Wholesale Trade",
    "3323": "Wholesale Trade",
    "333": "Wholesale Trade",
    "3331": "Wholesale Trade",
    "3332": "Wholesale Trade",
    "3339": "Wholesale Trade",
    "34": "Wholesale Trade",
    "341": "Wholesale Trade",
    "3411": "Wholesale Trade",
    "3419": "Wholesale Trade",
    "349": "Wholesale Trade",
    "3491": "Wholesale Trade",
    "3492": "Wholesale Trade",
    "3493": "Wholesale Trade",
    "3494": "Wholesale Trade",
    "3499": "Wholesale Trade",
    "35": "Wholesale Trade",
    "350": "Wholesale Trade",
    "3501": "Wholesale Trade",
    "3502": "Wholesale Trade",
    "3503": "Wholesale Trade",
    "3504": "Wholesale Trade",
    "3505": "Wholesale Trade",
    "36": "Wholesale Trade",
    "360": "Wholesale Trade",
    "3601": "Wholesale Trade",
    "3602": "Wholesale Trade",
    "3603": "Wholesale Trade",
    "3604": "Wholesale Trade",
    "3605": "Wholesale Trade",
    "3606": "Wholesale Trade",
    "3609": "Wholesale Trade",
    "37": "Wholesale Trade",
    "371": "Wholesale Trade",
    "3711": "Wholesale Trade",
    "3712": "Wholesale Trade",
    "372": "Wholesale Trade",
    "3720": "Wholesale Trade",
    "373": "Wholesale Trade",
    "3731": "Wholesale Trade",
    "3732": "Wholesale Trade",
    "3733": "Wholesale Trade",
    "3734": "Wholesale Trade",
    "3735": "Wholesale Trade",
    "3736": "Wholesale Trade",
    "3739": "Wholesale Trade",
    "38": "Wholesale Trade",
    "380": "Wholesale Trade",
    "3800": "Wholesale Trade",
    "39": "Automotive Retail",
    "391": "Automotive Retail",
    "3911": "Automotive Retail",
    "3912": "Automotive Retail",
    "3913": "Automotive Retail",
    "392": "Automotive Retail",
    "3921": "Automotive Retail",
    "3922": "Automotive Retail",
    "40": "Fuel Retail",
    "400": "Fuel Retail",
    "4000": "Fuel Retail",
    "41": "Retail Trade",
    "411": "Supermarkets and Grocery Retail",
    "4110": "Supermarkets and Grocery Retail",
    "4121": "Supermarkets and Grocery Retail",
    "4122": "Supermarkets and Grocery Retail",
    "4123": "Supermarkets and Grocery Retail",
    "4129": "Supermarkets and Grocery Retail",
    "42": "Retail Trade",
    "421": "Retail Trade",
    "4211": "Retail Trade",
    "4212": "Retail Trade",
    "4213": "Retail Trade",
    "4214": "Retail Trade",
    "422": "Retail Trade",
    "4221": "Retail Trade",
    "4222": "Retail Trade",
    "4229": "Retail Trade",
    "423": "Retail Trade",
    "4231": "Retail Trade",
    "4232": "Retail Trade",
    "424": "Retail Trade",
    "4241": "Retail Trade",
    "4242": "Retail Trade",
    "4243": "Retail Trade",
    "4244": "Retail Trade",
    "4245": "Retail Trade",
    "425": "Retail Trade",
    "4251": "Retail Trade",
    "4252": "Retail Trade",
    "4253": "Retail Trade",
    "4259": "Retail Trade",
    "426": "Retail Trade",
    "4260": "Retail Trade",
    "427": "Retail Trade",
    "4271": "Retail Trade",
    "4272": "Retail Trade",
    "4273": "Retail Trade",
    "4274": "Retail Trade",
    "4279": "Retail Trade",
    "43": "Retail Trade",
    "431": "Retail Trade",
    "4310": "Retail Trade",
    "432": "Retail Trade",
    "4320": "Retail Trade",
    "44": "Accommodation and Hospitality",
    "440": "Accommodation and Hospitality",
    "4400": "Accommodation and Hospitality",
    "45": "Accommodation and Hospitality",
    "451": "Accommodation and Hospitality",
    "4511": "Accommodation and Hospitality",
    "4512": "Accommodation and Hospitality",
    "4513": "Accommodation and Hospitality",
    "452": "Accommodation and Hospitality",
    "4520": "Accommodation and Hospitality",
    "453": "Accommodation and Hospitality",
    "4530": "Accommodation and Hospitality",
    "46": "Transport and Logistics",
    "461": "Transport and Logistics",
    "4610": "Transport and Logistics",
    "462": "Transport and Logistics",
    "4621": "Transport and Logistics",
    "4622": "Transport and Logistics",
    "4623": "Transport and Logistics",
    "47": "Transport and Logistics",
    "471": "Transport and Logistics",
    "4710": "Transport and Logistics",
    "472": "Transport and Logistics",
    "4720": "Transport and Logistics",
    "48": "Transport and Logistics",
    "481": "Transport and Logistics",
    "4810": "Transport and Logistics",
    "482": "Transport and Logistics",
    "4820": "Transport and Logistics",
    "49": "Aviation",
    "490": "Aviation",
    "4900": "Aviation",
    "50": "Transport and Logistics",
    "501": "Transport and Logistics",
    "5010": "Transport and Logistics",
    "502": "Transport and Logistics",
    "5021": "Transport and Logistics",
    "5029": "Transport and Logistics",
    "51": "Transport and Logistics",
    "510": "Transport and Logistics",
    "5101": "Transport and Logistics",
    "5102": "Transport and Logistics",
    "52": "Transport and Logistics",
    "521": "Transport and Logistics",
    "5211": "Transport and Logistics",
    "5212": "Transport and Logistics",
    "5219": "Transport and Logistics",
    "522": "Transport and Logistics",
    "5220": "Transport and Logistics",
    "529": "Transport and Logistics",
    "5291": "Transport and Logistics",
    "5292": "Transport and Logistics",
    "5299": "Transport and Logistics",
    "53": "Transport and Logistics",
    "530": "Transport and Logistics",
    "5301": "Transport and Logistics",
    "5309": "Transport and Logistics",
    "54": "Media and Entertainment",
    "541": "Media and Entertainment",
    "5411": "Media and Entertainment",
    "5412": "Media and Entertainment",
    "5413": "Media and Entertainment",
    "5414": "Media and Entertainment",
    "5419": "Media and Entertainment",
    "542": "Technology and Software",
    "5420": "Technology and Software",
    "55": "Media and Entertainment",
    "551": "Media and Entertainment",
    "5511": "Media and Entertainment",
    "5512": "Media and Entertainment",
    "5513": "Media and Entertainment",
    "5514": "Media and Entertainment",
    "552": "Media and Entertainment",
    "5521": "Media and Entertainment",
    "5522": "Media and Entertainment",
    "56": "Media and Entertainment",
    "561": "Media and Entertainment",
    "5610": "Media and Entertainment",
    "562": "Media and Entertainment",
    "5621": "Media and Entertainment",
    "5622": "Media and Entertainment",
    "57": "Media and Entertainment",
    "570": "Media and Entertainment",
    "5700": "Media and Entertainment",
    "58": "Telecommunications",
    "580": "Telecommunications",
    "5801": "Telecommunications",
    "5802": "Telecommunications",
    "5809": "Telecommunications",
    "59": "Technology and Software",
    "591": "Technology and Software",
    "5910": "Technology and Software",
    "592": "Technology and Software",
    "5921": "Technology and Software",
    "5922": "Technology and Software",
    "60": "Media and Entertainment",
    "601": "Media and Entertainment",
    "6010": "Media and Entertainment",
    "602": "Media and Entertainment",
    "6020": "Media and Entertainment",
    "62": "Banking",
    "6210": "Banking",
    "622": "Banking",
    "6221": "Banking",
    "6222": "Banking",
    "6223": "Banking",
    "6229": "Banking",
    "623": "Banking",
    "6230": "Banking",
    "624": "Asset Management and Investment",
    "6240": "Asset Management and Investment",
    "63": "Insurance and Superannuation",
    "631": "Life Insurance",
    "6310": "Life Insurance",
    "632": "Insurance",
    "6321": "Health Insurance",
    "6322": "General Insurance",
    "633": "Superannuation",
    "6330": "Superannuation",
    "64": "Financial Advisory and Broking",
    "641": "Financial Advisory and Broking",
    "6411": "Financial Advisory and Broking",
    "6419": "Financial Advisory and Broking",
    "642": "Financial Advisory and Broking",
    "6420": "Financial Advisory and Broking",
    "66": "Property and Real Estate",
    "661": "Property and Real Estate",
    "6611": "Property and Real Estate",
    "6619": "Property and Real Estate",
    "662": "Property and Real Estate",
    "6621": "Property and Real Estate",
    "6629": "Property and Real Estate",
    "663": "Property and Real Estate",
    "6631": "Property and Real Estate",
    "6632": "Property and Real Estate",
    "6633": "Property and Real Estate",
    "6634": "Property and Real Estate",
    "664": "Property and Real Estate",
    "67": "Property and Real Estate",
    "671": "Property and Real Estate",
    "6711": "Property and Real Estate",
    "6712": "Property and Real Estate",
    "672": "Property and Real Estate",
    "6720": "Property and Real Estate",
    "69": "Professional Services",
    "691": "Professional Services",
    "6910": "Professional Services",
    "692": "Professional Services",
    "6920": "Professional Services",
    "693": "Professional Services",
    "6931": "Professional Services",
    "6932": "Professional Services",
    "694": "Professional Services",
    "6940": "Professional Services",
    "6950": "Veterinary Services",
    "696": "Professional Services",
    "6960": "Professional Services",
    "697": "Professional Services",
    "6970": "Professional Services",
    "699": "Professional Services",
    "6990": "Professional Services",
    "70": "Professional Services",
    "700": "Professional Services",
    "7000": "Professional Services",
    "701": "Professional Services",
    "7010": "Professional Services",
    "702": "Professional Services",
    "7020": "Professional Services",
    "703": "Professional Services",
    "7030": "Professional Services",
    "709": "Professional Services",
    "7090": "Professional Services",
    "72": "Business Services",
    "721": "Business Services",
    "7211": "Business Services",
    "7212": "Business Services",
    "722": "Business Services",
    "7220": "Business Services",
    "729": "Business Services",
    "7291": "Business Services",
    "7292": "Business Services",
    "7299": "Business Services",
    "73": "Business Services",
    "731": "Business Services",
    "7311": "Business Services",
    "7312": "Business Services",
    "7313": "Business Services",
    "732": "Business Services",
    "7320": "Business Services",
    "75": "Government and Defence",
    "7530": "Government and Defence",
    "7540": "Government and Defence",
    "76": "Government and Defence",
    "7610": "Government and Defence",
    "7620": "Government and Defence",
    "7690": "Government and Defence",
    "77": "Government and Defence",
    "7700": "Government and Defence",
    "80": "Education and Training",
    "801": "Education and Training",
    "8010": "Education and Training",
    "802": "Education and Training",
    "8021": "Education and Training",
    "8022": "Education and Training",
    "8023": "Education and Training",
    "8024": "Education and Training",
    "81": "Education and Training",
    "8101": "Education and Training",
    "8102": "Education and Training",
    "811": "Education and Training",
    "812": "Education and Training",
    "82": "Education and Training",
    "821": "Education and Training",
    "8211": "Education and Training",
    "8219": "Education and Training",
    "822": "Education and Training",
    "8220": "Education and Training",
    "823": "Education and Training",
    "8230": "Education and Training",
    "829": "Education and Training",
    "8290": "Education and Training",
    "84": "Medical Services",
    "8401": "Hospitals",
    "8402": "Hospitals",
    "841": "Medical Services",
    "8411": "Medical Services",
    "8412": "Medical Services",
    "8419": "Medical Services",
    "842": "Medical Services",
    "8421": "Medical Services",
    "8422": "Medical Services",
    "8423": "Medical Services",
    "8424": "Dental Services",
    "8425": "Medical Services",
    "8426": "Medical Services",
    "8427": "Pharmacy",
    "8429": "Medical Services",
    "843": "Medical Services",
    "8431": "Dental Services",
    "8432": "Dental Services",
    "844": "Medical Services",
    "8440": "Medical Services",
    "85": "Aged Care",
    "851": "Aged Care",
    "8510": "Aged Care",
    "852": "Aged Care",
    "8520": "Aged Care",
    "86": "Social Assistance",
    "8601": "Social Assistance",
    "8609": "Social Assistance",
    "861": "Social Assistance",
    "869": "Social Assistance",
    "8690": "Social Assistance",
    "89": "Sport and Recreation",
    "890": "Sport and Recreation",
    "891": "Sport and Recreation",
    "8910": "Sport and Recreation",
    "892": "Sport and Recreation",
    "8921": "Sport and Recreation",
    "8922": "Sport and Recreation",
    "893": "Sport and Recreation",
    "8930": "Sport and Recreation",
    "899": "Sport and Recreation",
    "8990": "Sport and Recreation",
    "90": "Sport and Recreation",
    "900": "Sport and Recreation",
    "9001": "Sport and Recreation",
    "9002": "Sport and Recreation",
    "9003": "Sport and Recreation",
    "9009": "Sport and Recreation",
    "901": "Sport and Recreation",
    "902": "Sport and Recreation",
    "909": "Sport and Recreation",
    "91": "Gambling",
    "9101": "Gambling",
    "9102": "Gambling",
    "9103": "Gambling",
    "9109": "Gambling",
    "911": "Gambling",
    "912": "Gambling",
    "913": "Gambling",
    "92": "Sport and Recreation",
    "920": "Sport and Recreation",
    "9201": "Sport and Recreation",
    "9209": "Sport and Recreation",
    "921": "Sport and Recreation",
    "922": "Sport and Recreation",
    "94": "Other Services",
    "941": "Other Services",
    "9411": "Other Services",
    "9412": "Other Services",
    "9419": "Other Services",
    "942": "Other Services",
    "9421": "Other Services",
    "9422": "Other Services",
    "9429": "Other Services",
    "943": "Other Services",
    "9431": "Other Services",
    "9432": "Other Services",
    "95": "Other Services",
    "951": "Other Services",
    "9511": "Other Services",
    "9512": "Other Services",
    "952": "Other Services",
    "9521": "Other Services",
    "9529": "Other Services",
    "953": "Other Services",
    "9531": "Other Services",
    "9532": "Other Services",
    "9533": "Other Services",
    "9534": "Other Services",
    "9539": "Other Services",
    "96": "Other Services",
    "963": "Other Services",
    "964": "Other Services",
    "965": "Other Services",
    "969": "Other Services",
    "A": "Agriculture and Agribusiness",
    "B": "Mining",
    "C": "Manufacturing",
    "D": "Energy and Utilities",
    "E": "Construction and Engineering",
    "F": "Wholesale Trade",
    "G": "Retail Trade",
    "H": "Accommodation and Hospitality",
    "I": "Transport and Logistics",
    "J": "Media and Entertainment",
    "K": "Financial and Insurance Services",
    "L": "Property and Real Estate",
    "M": "Professional Services",
    "N": "Business Services",
    "O": "Government and Defence",
    "P": "Education and Training",
    "Q": "Social Assistance",
    "R": "Sport and Recreation",
    "S": "Other Services",
}


def get_ma_sector(anzsic_code: str) -> str:
    """
    Map an ANZSIC code to an M&A sector label.

    Tries the code as-is first (handles 4-digit class codes), then
    falls back progressively to 3-digit group, 2-digit subdivision,
    and 1-character division, so partial codes still resolve.

    Returns "Unknown / Other" if the code is not recognised.
    """
    if not anzsic_code:
        return ""

    code = str(anzsic_code).strip()

    # Direct lookup (handles all levels: letter, 2-, 3-, 4-digit)
    if code in ANZSIC_TO_MA_SECTOR:
        return ANZSIC_TO_MA_SECTOR[code]

    # Progressive fallback for 4-digit class codes
    if len(code) == 4 and code.isdigit():
        if code[:3] in ANZSIC_TO_MA_SECTOR:
            return ANZSIC_TO_MA_SECTOR[code[:3]]
        if code[:2] in ANZSIC_TO_MA_SECTOR:
            return ANZSIC_TO_MA_SECTOR[code[:2]]

    return "Unknown / Other"


def get_ma_sectors_for_entry(anzsic_codes_field: str) -> list[str]:
    if not anzsic_codes_field:
        return []
    import re
    sectors = []
    seen = set()
    for chunk in str(anzsic_codes_field).split(";"):
        # Extract leading digits only (e.g. "1852 Cosmetic..." -> "1852")
        m = re.match(r"\s*(\d+)", chunk)
        if not m:
            continue
        sector = get_ma_sector(m.group(1))
        if sector and sector != "Unknown / Other" and sector not in seen:
            sectors.append(sector)
            seen.add(sector)
    return sectors
